-- Add payment gateway configuration columns to platform_settings
ALTER TABLE platform_settings
  ADD COLUMN IF NOT EXISTS stripe_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS stripe_mode TEXT DEFAULT 'test',
  ADD COLUMN IF NOT EXISTS stripe_publishable_key TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS stripe_webhook_secret TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS cash_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS cash_instructions TEXT DEFAULT 'Please pay the cleaner in cash after the service is completed.',
  ADD COLUMN IF NOT EXISTS cash_confirmation_required BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS bank_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS bank_name TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_account_name TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_account_number TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_routing_number TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_swift_code TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_instructions TEXT DEFAULT 'Please transfer the payment before your scheduled booking date.',
  ADD COLUMN IF NOT EXISTS auto_payouts_enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS payout_schedule TEXT DEFAULT 'weekly',
  ADD COLUMN IF NOT EXISTS minimum_payout_amount NUMERIC DEFAULT 50,
  ADD COLUMN IF NOT EXISTS payout_delay_days INTEGER DEFAULT 7,
  ADD COLUMN IF NOT EXISTS capture_method TEXT DEFAULT 'automatic',
  ADD COLUMN IF NOT EXISTS allow_refunds BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS refund_window_days INTEGER DEFAULT 14,
  ADD COLUMN IF NOT EXISTS pass_processing_fee_to_customer BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS processing_fee_percentage NUMERIC DEFAULT 2.9;
